---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(readxl)
```

## Download the data

```{r}
# download arrests file
download.file("https://raw.githubusercontent.com/utdata/chj-r-introduction/main/chj-day1-p2/data-raw/APD_marijuana_arrests_2016-2020_data.xlsx", "data-raw/apd-pot-arrests.xlsx")
```

## First import try

```{r}
read_excel(
  "data-raw/apd-pot-arrests.xlsx"
)
```

## Adding the sheet designation

```{r}
read_excel(
  "data-raw/apd-pot-arrests.xlsx",
  sheet = "Results"
)
```


## Add the column types

```{r import}
read_excel(
  "data-raw/apd-pot-arrests.xlsx",
  sheet = "Results",
  col_types = c(
    "text",
    "guess",
    "guess",
    "guess",
    "guess",
    "guess",
    "text",
    "guess",
    "guess"
    )
  ) %>% 
  glimpse()
```

## Clean the names

```{r}
read_excel(
  "data-raw/apd-pot-arrests.xlsx",
  sheet = "Results",
  col_types = c(
    "text",
    "guess",
    "guess",
    "guess",
    "guess",
    "guess",
    "text",
    "guess",
    "guess"
    )
  ) %>% 
  clean_names() %>% 
  glimpse()
```

## Save the tibble

```{r}
arrests <- read_excel(
  "data-raw/apd-pot-arrests.xlsx",
  sheet = "Results",
  col_types = c(
    "text",
    "guess",
    "guess",
    "guess",
    "guess",
    "guess",
    "text",
    "guess",
    "guess"
    )
  ) %>% 
  clean_names()

arrests %>% 
  glimpse()
```




